version: 2
jobs:
  # test website job
  test_web:
    working_directory: ~/project/web
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          # install dependencies
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          # linting
          name: Linting
          command: npm run lint
      - run:
          # test
          name: Test
          command: npm run test
          environment:
            JUNIT_REPORT_PATH: reports/
            JUNIT_REPORT_NAME: test-results.xml
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
  # build website job
  build_web:
    working_directory: ~/project/web
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          # install dependencies
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          # configure angular environment
          name: Configure environment
          command: npm run configure-env
          environment:
            PORTFOLIO_ENV: staging
      - run:
          name: Build Website
          command: npm run build
      - store_artifacts:
          path: dist/
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test_web
      - build_web:
          requires:
            - test_web
          filters:
            branches:
              only:
                - master
